version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/FunctionalProgrammingDemo/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "nuget"
    directory: "/FunctionalProgrammingDemo.TestsV3/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
